# Generated by Django 3.2 on 2021-06-08 11:18

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'auctions/fixtures/User.json')
    call_command('loaddata', 'auctions/fixtures/BidIncrement.json')
    call_command('loaddata', 'auctions/fixtures/Category.json')


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]

