# Generated by Django 3.2 on 2021-05-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_bidunit_bidincrement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidincrement',
            old_name='unit_price',
            new_name='increment',
        ),
    ]
