# Generated by Django 3.2 on 2021-05-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingproduct',
            old_name='upset_price',
            new_name='start_price',
        ),
    ]
